//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDetails
    {
        public int DetailId { get; set; }
        public string EmpNo { get; set; }
        public string PhoneNo { get; set; }
        public string FullAddress { get; set; }
    
        public virtual Emp Emp { get; set; }
    }
}
