//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17_Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PuneDB : DbContext
    {
        public PuneDB()
            : base("name=PuneDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Table> Tables { get; set; }
        public DbSet<Test> Tests { get; set; }
        public DbSet<Emp> Emps { get; set; }
        public DbSet<EmpDetails> EmpDetails { get; set; }
    }
}
